defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  

use_wandb: False
data_dir: /home/andliao/workspace/course/csc2611-course-semantic-change/project/datasets/semeval2020_ulscd_eng
snapshot_dir: /home/andliao/workspace/course/csc2611-course-semantic-change/project/outputs/vocab_size_3000-batch_size_256
max_length: 128
seed: 123
mlm_probability: 0.15

per_device_batch_size: 64
hessian_approx: 
  batch_size: 1
  num_samples: 1
  scale: 1000
  damping: 1e-2
  recursion_depth: 10000

weight_decay: 0.01
num_proc: 2
