defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  

use_wandb: False
data_dir: /home/andliao/workspace/course/csc2611-course-semantic-change/project/datasets/semeval2020_ulscd_eng/full_corpus
vocab_size: 10000
max_length: 512
min_frequency: 2
seed: 123
mlm_probability: 0.15

per_device_train_batch_size: 8
per_device_eval_batch_size: 8

learning_rate: 5e-5

num_warmup_steps: 0
gradient_accumulation_steps: 1
max_train_steps: "???"
num_train_epochs: 5
weight_decay: 0.
lr_scheduler_type: linear
